import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./components/ClientProvider";

export const metadata: Metadata = {
  title: "Todothat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
