import type { Metadata } from "next";

import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import LeftsideBar from "./components/LeftsideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <LeftsideBar />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>

      </body>
    </html>
  );
}
